server:
  port: 8081

spring:
  application:
    name: posctn-api

  # Database connection config
  datasource:
    url: jdbc:postgresql://localhost:5432/POSCTM
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  # JPA Connection config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Liquibase config
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

---

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---

# JWT config
jwt:
  secret-key: 25101917875e8390ecd5b749583354a84f2401c45d834d943a9d0fb0376ee1fd
  expiration: 604800000
  refresh-expiration: 604800000


